# Generated by Django 3.2.7 on 2022-03-01 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(primary_key=True, serialize=False)),
                ('province_code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('producer_id', models.AutoField(primary_key=True, serialize=False)),
                ('producer_name', models.CharField(max_length=20, unique=True)),
                ('producer_cost', models.IntegerField()),
                ('producer_production', models.IntegerField()),
                ('province_id', models.ForeignKey(db_column='province_id', on_delete=django.db.models.deletion.CASCADE, to='production.province')),
            ],
        ),
    ]
